# Generated by Django 4.2.7 on 2023-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_answerone_question_answertwo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceOne', models.CharField(max_length=30)),
                ('choiceTwo', models.CharField(max_length=30)),
                ('choiceThree', models.CharField(max_length=30)),
                ('choiceFour', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerOne',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerTwo',
            field=models.CharField(max_length=30),
        ),
    ]
