# Generated by Django 4.2.7 on 2023-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='human',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerFour',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answerThree',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceFive',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceSeven',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceSix',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answerFour',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answerThree',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
