# Generated by Django 4.2.7 on 2023-12-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_race_character_human_answer_answerfour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='charClass',
            new_name='range',
        ),
    ]
