# Generated by Django 4.2.7 on 2023-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_charclass_character_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='range',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='support',
            field=models.CharField(max_length=30),
        ),
    ]
