# Generated by Django 4.2.7 on 2023-12-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_choice_choiceeight_choice_choicenine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceEight',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceFive',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceFour',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceNine',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceOne',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceSeven',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceSix',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceThree',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceTwo',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
